### PR TITLE
Fix TypeError in select_graphic_rendition

### LINKED ISSUE #202: TypeError in select_graphic_rendition handler (argument private) from SGR sequence ESC[?4m
### Description
  When processing terminal output from vim 9.0+, pyte crashes with a `TypeError` due to `select_graphic_rendition()` method not accepting the `private` keyword argument that is passed by the CSI parser for private escape sequences.

  ### Background on ESC[?4m Sequence
  The `ESC[?4m` sequence appears in vim 9.0+ as a terminal control sequence that is not a standard SGR underline command (which would be `ESC[4m`). This private sequence is used by vim for terminal compatibility but is not universally
  supported by all terminals. Some terminals display it as literal text, while others (like pyte) attempt to process it and crash due to the private parameter.

  **Note**: This is different from standard SGR sequences:
  - `ESC[4m` = standard underline SGR sequence
  - `ESC[?4m` = private sequence used by vim 9.0+

  **Related Issues & Documentation:**
  - [WindTerm Issue #1623](https://github.com/kingToolbox/WindTerm/issues/1623) - ESC[?4m displayed when vim opens files
  - [Stack Overflow](https://stackoverflow.com/questions/75318113/i-compile-vim9-by-my-self-but-esc4m-keeps-showing-up-whyhow-to-fix-this) - ESC[?4m appearing in compiled vim9

  ### Error
  TypeError: Screen.select_graphic_rendition() got an unexpected keyword argument 'private'

  ### Root Cause
  The issue was introduced in commit a12d472 (January 2016) when the parser was refactored to pass `private=True` directly as a keyword argument, but the handler methods in `screens.py` were never updated to accept this parameter.

  In `streams.py:354`:
  ```python
  if private:
      dispatch(csi[char], *params, private=True)  # This passes private=True
```

  But Screen.select_graphic_rendition() signature doesn't accept **kwargs:
```python  
def select_graphic_rendition(self, *attrs: int) -> None:  # Missing **kwargs
```

  Reproduction

```python
  import pyte
  screen = pyte.HistoryScreen(80, 24)
  stream = pyte.ByteStream(screen)
  stream.feed(b'\x1b[?4m')  # Private SGR sequence from vim 9.0+

  Full stacktrace:
  Traceback (most recent call last):
    File "test.py", line 4, in <module>
      stream.feed(b'\x1b[?4m')
    File "/path/to/pyte/streams.py", line 425, in feed
      super().feed(data_str)
    File "/path/to/pyte/streams.py", line 206, in feed
      taking_plain_text = send(data[offset:offset + 1])
    File "/path/to/pyte/streams.py", line 214, in _send_to_parser
      return self._parser.send(data)
    File "/path/to/pyte/streams.py", line 354, in _parser_fsm
      dispatch(csi[char], *params, private=True)
    File "/path/to/pyte/screens.py", line 1157, in inner
      result = handler(*args, **kwargs)
  TypeError: Screen.select_graphic_rendition() got an unexpected keyword argument 'private'
```
 ### Impact

  - Affects vim 9.0+ terminal output processing
  - Any application sending private SGR escape sequences will crash pyte
  - Particularly affects terminal emulators and automation tools processing vim output

  ### Environment

  - pyte version: 0.8.2+ (including latest development version)
  - Python: 3.x (all versions)
  - vim: 9.0+ (when ESC[?4m sequence was introduced)

  ### Expected Behavior

  Private SGR sequences should be ignored gracefully without crashing, consistent with VT terminal behavior.

### PR DESCRIPTION
**Pull request by mustitz**
Fixes #202

- Add `private` parameter to select_graphic_rendition() method signature
- Handle `private=True` parameter by returning early (no-op for private SGR sequences)

### CODE REVIEW

File: pyte/screens.py [hunk 1]
```diff
@@ -971,11 +971,14 @@ def alignment_display(self) -> None:
             for x in range(self.columns):
                 self.buffer[y][x] = self.buffer[y][x]._replace(data="E")
 
-    def select_graphic_rendition(self, *attrs: int) -> None:
+    def select_graphic_rendition(self, *attrs: int, **kwargs: Any) -> None:
```
Comment (superbobry) [inline pyte/screens.py]: Can this be `private: bool = False` so that we don't allow arbitrary kwargs here?

Comment (mustitz) [reply pyte/screens.py]: Yes, you're absolutely right. Using `private: bool = False` is much better than `**kwargs`.

I used the existing `**kwargs` pattern as a reference from other methods in the codebase, but you're correct that explicit parameters are better. I noticed that `set_mode()`, `reset_mode()`, `erase_in_display()`, and `report_device_attributes()` also use the same pattern for the private parameter. Should I refactor those methods for consistency as well?

Comment (superbobry) [reply pyte/screens.py]: Let's keep the rest as is and only change `select_graphic_rendition`.

Comment (mustitz) [reply pyte/screens.py]: Done

**Review by superbobry — APPROVED** [review]
Thanks!

**Comment by superbobry** [comment]
Would you mind adding a test for this to avoid regressions in the future?

**Comment by mustitz** [comment]
> Would you mind adding a test for this to avoid regressions in the future?

Done

**Review by superbobry — APPROVED** [review]
